### ISSUE TITLE
Hotkey Support

### ISSUE THREAD

**Issue by MatthewAry** [surrealdb/surrealist#107]
**Describe your feature request**
Would like to see hotkey support added for quick manipulation. For example in the designer view, hotkeys to create tables, add fields, etc.

**Are you willing to contribute this feature?**
Maybe, depends on my time and motivation.

**Related pull request (if applicable)**
N/A

**Comment by oskar-gmerek** [comment]
I'd like to add my two cents. I would like to bring attention to a specific matter, in version 1.1.0, the initial hotkey implementation is evident. It would be advantageous to incorporate a feature that allows users to modify default hotkeys or enforce the use of Surrealist hotkeys when the Surrealist window is active.

For instance, in version 1.1.0, the 'F11' hotkey, intended for pinning the window, creates conflicts with my preset keyboard shortcut (volume down) and also interferes with the default macOS hotkey for opening sound settings (Option+F11).

While hotkeys can greatly enhance user experience, they can also become a source of frustration if implemented without comprehensive user control and without adhering to an opt-in approach.

**Comment by macjuul** [comment]
Good point @oskar-gmerek. I'm definitely interesting in expanding Surrealist with additional hotkeys. If I do so I'll implement a new settings dialog tab to make each one customizable.

@MatthewAry do you have any further specific ideas and examples of hotkeys you would like to see?

**Comment by macjuul** [comment]
Saving this here since it's relevant to this issue. Here is a list of currently existing hotkeys.

- `F11` to toggle always on top
- `ctrl + s` to start or stop the local server
- `F9` and `ctrl + enter` to execute the current query (query view)
- `ctrl + left arrow` to switch to the previous view
- `ctrl + right arrow` to switch to the next view
- `ctrl + 1` through `ctrl + 0` switch to the session of that index

additionally the query editors use monaco and thus include a whole array of useful hotkeys including

- `ctrl + F` to search
- `ctrl + R` to replace
- `ctrl + space` to manually open the table suggestions
- `F1` for the command palette (also shows more available hotkeys)
- not a hotkey but when you select (part of) a query you can right click and hit "Execute selection", useful if you want to test individual or inner queries

these exist work but are broken in the latest release

- `ctrl + n` to create a new session
- `ctrl + alt + minus` to decrease editor font size
- `ctrl + alt + equals` to increase editor font size
- `ctrl + alt + 0` to reset editor font size

Keep in mind some hotkeys only work when inside of an editor, while some others may only work outside

**Comment by MatthewAry** [comment]
Nice! Could a key map be added so we can see these in Surrealist?

**Comment by macjuul** [comment]
This has now been partially implemented in the form of the command palette (`cmd + K` or `ctrl + K`) in Surrealist 2.0, which allows navigating to any part of the interface and triggering most actions available in the UI.

Additionally I have plans to further expand hotkey functionality in the future

**Comment by Z8MB1E** [comment]
@macjuul Is there any reason why the editor keybinds don't work? I recently updated to 2.0.2 and I can no longer quickly trigger comments on query lines, manually complete suggestions, etc... `CTRL-Space` doesn't work, `CTRL-/` doesn't work, none of those keybinds seem to work for me anymore. Any ideas what I might need to do if it's not an issue for anyone else?

**Comment by macjuul** [comment]
I changed the implementation of the editor for various performance reasons. While there is a change in keybinds, both `Ctrl + Space` and `Ctrl + /` were supposed to work and will be fixed in the next patch release
