### ISSUE TITLE
Unable to run Surrealist on Arch Linux

### ISSUE THREAD

**Issue by ASoldo** [surrealdb/surrealist#203]
**Describe the bug**
Today I have removed old `Surrealist` app and installed new one with `yay -S surrealist` and when I try to run it I see this message in terminal:

```bash
❯ surrealist
surrealist: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Install fresh Surrealist with yay -S surrealist
2. run `surrealist`

**Expected behavior**
Run application from Rofi/Terminal as before

**Environment:**
Arch Linux

**Comment by rynoV** [comment]
There's some comments in the aur page that should help for now https://aur.archlinux.org/packages/surrealist-bin

I also noticed the UI lags significantly if I don't run with `WEBKIT_DISABLE_DMABUF_RENDERER=1`

**Comment by tacheometry** [comment]
The package includes the `WEBKIT_DISABLE_DMABUF_RENDERER=1` patch to the `.desktop` file now. For running it from the CLI you'll still have to add that variable in one way (such as through bashrc or writing it every time).

**Comment by DelSkayn** [comment]
The AUR package is currently supplied by the community and we don't support it officially yet. If you have any problems with the AUR package please raise it on the [AUR package itself](https://aur.archlinux.org/packages/surrealist-bin) so @tacheometry the maintainer of the package can handle it.

**Comment by ASoldo** [comment]
For now I'm using .AppImage and it works and I didn't need to add `WEBKIT_DISABLE_DMABUF_RENDERER=1` for it to work. I can work with this now. I hope AUR package will be fixed in the future.

**Comment by tacheometry** [comment]
It isn't the fault of the package. It is an upstream issue of webkit2gtk interacting with Nvidia graphics drivers. The AUR package just extracts the deb file: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=surrealist-bin

**Comment by ASoldo** [comment]
@tacheometry I see, tnx. What is the optimal way to install this/updated version on Arch? I can see in releases .AppImage and .deb, am I missing something here?

**Comment by tacheometry** [comment]
The package uses the .deb file from the releases and extracts it. Because the deb contains a plain executable, it also runs on Arch with the right dependencies. To install the latest version update your system (`yay` or `yay -Syu` - using `yay -Sy` is not recommended), then install the package `yay -S surrealist-bin`.

The only way to get it showing properly on Nvidia is using that `WEBKIT_DISABLE_DMABUF_RENDERER=1`. If you open Surrealist with the `.desktop` file, like clicking in your DE's Start menu (like Xfce's Whisker menu), it's already set for you. Otherwise add it to your `.bashrc` and running `surrealist` from the CLI should also work

**Comment by tacheometry** [comment]
@ASoldo Ah ok, I was typing just as you edited that haha
