### ISSUE TITLE
Wont start on Ubuntu after install

### ISSUE THREAD

**Issue by mocox** [surrealdb/surrealist#235]
**Describe the bug**
I installed surrealist on my ubuntu desktop, i can see the icon on my apps page but when i click it, it seems to try to open but i get no GUI and there is no process running for it.

**To Reproduce**
1. downloaded deb package
2. installed using gdeb
3. tried to run via icon on apps page
4. No gui starts and no process running

**Expected behavior**
Should start

**Environment:**
Linux

Paste your environment here by following these steps
Ubuntu 23.10
```

**Comment by OmanF** [comment]
Having the same issue, when trying to start the app from the CLI, I believe the issue is one of `can't open shared resources, missing libssl.so.1.1` (even though my machine, Linux Mint Virginia 21.3, **does have** `libssl.so.3.0` installed, after it's was built from source downloaded at `openssl.org`).

**Comment by dayo777** [comment]
I am also facing this issue on Ubuntu Desktop. I installed v2.0.3 but it would not open.

**Comment by mocox** [comment]
Apparently it will be fixed in the next release, i asked on discord and the developer replied.

**Comment by macjuul** [comment]
This should have been fixed in a recent release
