### ISSUE TITLE
Windows update fails

### ISSUE THREAD

**Issue by cope** [surrealdb/surrealist#317]
When I open Surrealist, I get this popup:
![image](https://github.com/surrealdb/surrealist/assets/112515/504a79fb-ab1f-44a8-9164-a10b30a25be5)
so I click Yes, and then I get another popup which I cannot screenshot, but I am assuming is probably related to #316, where I again click Yes and I am taken back to my existing Surrealist version which throws the above popup and this cycle repeats indefinitely.

So, I thought OK, I will just download the latest version and install it.

However, when I do that I only get the remove option available:
![image](https://github.com/surrealdb/surrealist/assets/112515/ef94888f-f1af-4610-90f2-9f36a642947a)

So I thought OK, maybe that will be the first step - it wasn't. It was the only step and afterwards Surrealist old version was still there...

The only way I was able to get it working was to manually uninstall the existing version, then install the new one.

IMHO, this is not how the update experience should be.

**Comment by formula349** [comment]
I had the same experience

**Comment by macjuul** [comment]
I cannot reproduce this issue myself, however I do know this can happen when you previously installed Surrealist using an .exe installer, which was unintentionally included in a previous release. This is also why Surrealist would appear to be installed twice. Additionally due to some low level technical changes in 2.1 the behaviour of the installer may differ from previous versions.

This shouldn't happen anymore going forward, however if this issue keeps persisting please do open a new issue so I can look deeper into it.
