### ISSUE TITLE
Surrealist opens but shows no interface/GUI

### ISSUE THREAD

**Issue by Mauge9638** [surrealdb/surrealist#353]
**Describe the bug**
I expect the interface/GUI to load, when hovering over different parts of the application it seems like it has loaded some parts correctly, but the GUI just doesn't show/load properly.

![image](https://github.com/surrealdb/surrealist/assets/55133846/086fa50f-bb54-497c-946f-a51cae0968ba)

**To Reproduce**
1. Be on Ubuntu 24.04
2. Open Surrealist App

**Expected behavior**
I expect the interface/GUI to actually be visible

**Environment:**
Ubuntu 24.04
Surrealist 2.1.2
SurrealDB 1.5.1

**Comment by macjuul** [comment]
Could you check if [this workaround](https://github.com/surrealdb/surrealist/issues/276#issuecomment-2203244788) solves the issue?

**Comment by Mauge9638** [comment]
> Could you check if [this workaround](https://github.com/surrealdb/surrealist/issues/276#issuecomment-2203244788) solves the issue?

Running:
`WEBKIT_DISABLE_DMABUF_RENDERER=1 surrealist` did fix it

**Comment by OmanF** [comment]
This workaround works **but** it requires starting Surrealist via the CLI (as opposed to from the start menu), and also "captures" the terminal window in which it was started (for obvious reasons. Also, starting it with `&` doesn't do the trick since the logger keep "polluting" the terminal even though the process itself is run in the background).

Trying adding this to the startup command of the AppImage failed for me (or I don't know how to do it correctly, which **effectively** is the same).

All in all, yes, as a **workaround** it works, but for v3.0.8 you'd want your app to stop having this issue (a quick search for `start`, `linux`, `mint`, `ubuntu`, and `arch` in both open and closed issues shows this issue is **extremely** common and recurring in every iteration of the app... and Surrealist being the de-facto **only** (current) way to visually interact with SurrealDB, it having so many issues starting up is a **major** reason to not use SurrealDB at all... which is a shame, since it definitely gives its main competitor, ArangoDB, a run for its money, saying this as a production user of ArangoDB that is considering switching).

**Comment by macjuul** [comment]
Hi @OmanF, I fully understand your frustration and would like to get this resolved. See [this comment](https://github.com/surrealdb/surrealist/issues/276#issuecomment-2464421294) for an update regarding this issue

**Comment by OmanF** [comment]
Thank you and much appreciated.
I'll try building the new client from source myself and see if it does magic.

Either way, appreciate you taking user input as seriously as you do!
(And love your product. I'm dead serious about thinking about switching).
